### ISSUE TITLE
Update Conversion from Mapping.xlsx to Mapping-v15.1.json files

### ISSUE THREAD

**Issue by allan-korol** [glowbase/decider#12]
I would suggest that the **name,** **description,** **url,** etc would probably be best suited directly under the mitigation, with a 'list' of techniques it addresses. In the proposed form, it implies that given a mitigation, each technique would have a different **name,** **description,** etc for the mitigation.

```json
{
    "M1234": {
        "name": "Software Configuration",
        "description": "Some description goes here.",
        "source": "MITRE",
        "techniques": {
            "T1234.001": {
                "use": "some use"
            },
            "T1234.002": {
                "use": "some use"
            },
        }
    },
    "ISM-1122": {
        "name": "Software Configuration",
        "description": "Some description goes here.",
        "source": "ISM",
        "techniques": [
            "T1223.001",
            "T4545.002",
            "T4326.001"
        ]
    }
}
```

This method would simplify the loading of data from the mappings spreadsheet as you will be able to load all the mitigations and their **descriptions/details,** and then enumerate the Technique sheet and simply find and attach the technique to the list for the  mitigations' **_techniques_** field.

**Comment by glowbase** [comment]
Format for *tools.json*.

```json
[
    {
        "tool": "Name of tool",
        "src": {
            "type": "url",
            "ref": "https://tool.com"
        },
        "techniques": {
            "T1234.001": {
                
            }
        }
    }
]
```

**Comment by glowbase** [comment]
![image](https://github.com/user-attachments/assets/7a95da0d-f529-4725-b688-b1f2f5e68d5b)

What would be the best way to implement this into the current working format for mappings-v15.1.json @allan-korol?

**Comment by allan-korol** [comment]
@glowbase, this is probably going to be extensive information but may tie into evidence locations and tools and really start to tie everything together.

My initial thought would be something like an "evidence source" (eg file and it's location, OS, etc).

We could then represent an "artefact" that is linked to an "evidence source" (and probably a tool), along with some extra details (where the event id would be represented.

Might even consider a specific "event" table (as opposed to an "artefact" table), but I think the important part would be to link to the source, technique, and tool.

I would be more inclined to explore an "event" table at this point, and consider merging into a generic "artefact" table later if appropriate.

**Comment by glowbase** [comment]
@allan-korol , surprisingly the NIST documentation doesn't have a description for those two controls. I think the plan is to just remove those two controls from being used.

**Comment by allan-korol** [comment]
@glowbase the initial description of the issue discussed a new format and was extended for the uses.

I noticed that the actually convert_new.py script was bit of both, it was an array of objects with the technique as the key, and an object of use. I will adjust the script so it's in line with the first. An object of techniques, with the key being the Technique ID, and the value being an object of the use.

Current:
```json
{
    "M1234": {
        "name": "Software Configuration",
        "description": "Some description goes here.",
        "source": "MITRE",
        "techniques": [
            {
               "T1234.001": {
                     "use": "some use"
               }
            },
            {
               "T1234.002": {
                     "use": "some use"
                }
            }
        ]
    }
}
```

Updated:
```json
{
    "M1234": {
        "name": "Software Configuration",
        "description": "Some description goes here.",
        "source": "MITRE",
        "techniques": {
            "T1234.001": {
                "use": "some use"
            },
            "T1234.002": {
                "use": "some use"
            }
        }
    }
}
```

**Comment by allan-korol** [comment]
I recommend closing this issue now the new mapping is imported with PR #15 and opening new ones for things like evidence, artefacts, events, etc.
