### ISSUE TITLE
convert.py is broken due to column changes

### ISSUE THREAD

**Issue by allan-korol** [glowbase/decider#9]
_Problem encountered while build the database import and the need to generate a new mappings.json file which includes some extra fields._

It appears that there may have been some column renaming has occurred as the convert.py file expects 'remediations' but in the current version it is 'Mitigation / Remediation'

**Comment by glowbase** [comment]
Changes to the 'MITRE Controls' table within the *mappings.xlsx* spreadsheet has changed format as well which will require *convert.py* to be updated.

**Comment by glowbase** [comment]
NIST controls now have a new format. AC-4 instead of AC-04.

**Comment by allan-korol** [comment]
I have modified my local copy of the mappings.json file; note there is a rename to include the version for consistency with the existing decider, and to ensure that mitigations are loaded for techniques of the specific version. Any changes, such as format of control identifiers, should not impact the database import (PR to come soon), as long as it is referenced the same throughout the database.

**Comment by glowbase** [comment]
[mappings.xlsx](https://github.com/user-attachments/files/16611912/Master.MITRE.Mapping.xlsx)

Updated *mappings.xlsx*.
- *MITRE Controls* is now *MITRE v15 Controls*. Each technique is mapped to its own MITRE mitigation. The format is drastically different, *convert.py* will need to be adjusted.

Format for MITRE Mitigations could be:
```json
"M1234": [
    "T1234.001": {
        "name": "Software Configuration",
        "description": "Some description goes here."
    }
]
```

**Comment by allan-korol** [comment]
I would suggest that the **name,** **description,** **url,** etc would probably be best suited directly under the mitigation, with a 'list' of techniques it addresses. In the proposed form, it implies that given a mitigation, each technique would have a different **name,** **description,** etc for the mitigation.

```json
{
    "M1234": {
        "name": "Software Configuration",
        "description": "Some description goes here.",
        "url": "http://abc.com/M1234",
        "source": "MITRE",
        "techniques": [
            "T1234.001",
            "T4321.002"
        ]
    },
    "ISM-1122": {
        "name": "Software Configuration",
        "description": "Some description goes here.",
        "url": "http://ism.com/M1234",
        "source": "ISM",
        "techniques": [
            "T1223.001",
            "T4545.002",
            "T4326.001"
        ]
    }
}
```

This method would simplify the loading of data from the mappings spreadsheet as you will be able to load all the mitigations and their **descriptions/details,** and then enumerate the Technique sheet and simply find and attach the technique to the list for the  mitigations' **_techniques_** field.
